### ISSUE TITLE
index redirect and default fields re-activation

### ISSUE THREAD

**Issue by marflow** [mmikkel/DashCols-Craft#1]
Hello Mikkel,
Thank you for developing DashCols, nice addition to the CP! Playing around I noticed two little issues:
– after saving settings for Singles, DashCols tries to load ..."admin/singles", should be "admin/entries/singles". 
– after deactivating standard date fields, reactivating them does´t bring them back.
Thanks for looking into that.

**Comment by mmikkel** [comment]
Whoa, those are embarrassing. Thx for reporting - I'm on it.

**Comment by mmikkel** [comment]
Just pushed an update fixing the redirect issue – look for version 1.1.2.

The other issue related to default fields I'm unable to reproduce – however not all listings have all the default fields built in; i.e. _Singles_ only have URI, not postDate nor expiryDate; hence disabling/enabling those will do nothing.

I admit it's confusing to be able to "disable" a default fields which doesn't actually relate to the listing in question, so I'll probably tweak the editing template to exclude any fields which aren't relevant at any time.

Thanks!

**Comment by marflow** [comment]
Thanks for the quick fix! Regarding the second issue I was´t sure but obviously confused because of the options for the Singles pages. Sorry for the confusion!

**Comment by mmikkel** [comment]
No worries, again - thanks for reporting.

**Comment by mmikkel** [comment]
I'll edit the options so it's less confusing going forward :)
