### ISSUE TITLE
Feature Request - Entry Types

### ISSUE THREAD

**Issue by mildlygeeky** [mmikkel/DashCols-Craft#11]
Love this plugin, but would love to see Entry Type be a possible field (guessing it would have to be in the Show/hide metadata section)

**Comment by mmikkel** [comment]
Thank you for the kind words and the FR, @mildlygeeky. An Entry Type column would be a doable, nice addition – look for it in a future update.

**Comment by richhayler** [comment]
Yes please - this would be a great addition!

**Comment by mmikkel** [comment]
@richhayler A sortable Entry Type column is now available under Show/hide metadata. Thanks again!
