### ISSUE TITLE
Unnecessary tab control?

### ISSUE THREAD

**Issue by lindseydiloreto** [mmikkel/DashCols-Craft#15]
Now that [CP Nav](https://github.com/engram-design/CPNav) exists, you may not need to give people the ability to hide or rename the CP tab anymore. I'm guessing that many people will install these two plugins together. (I know I will!)

Just my 2 cents. :)

**Comment by mmikkel** [comment]
I concur, and will probably remove that option in a future update. Thanks for your input! :+1:

**Comment by lindseydiloreto** [comment]
Sweet, no problem! :)

**Comment by mmikkel** [comment]
I took my sweet time, but the option is now removed :)

**Comment by lindseydiloreto** [comment]
Ha, sweet! Thanks man!
