### ISSUE TITLE
There is a way to easily add field ?

### ISSUE THREAD

**Issue by rdomingue** [mmikkel/DashCols-Craft#23]
I'm using Doxter for some of my body's entries.
Your plugin gives me : Unknown class: Craft\DoxterModel
There is a way I can easily added it ?
In fact, it could be plain text and used the same process as richtext.

Thank you

**Comment by mmikkel** [comment]
Hello @rdomingue! Unfortunately, no – not yet. This is something I'm looking to solve with DashCols for Craft 3, which will probably be a complete rewrite.

For now, I just added support for Doxter – look for version 1.2.4 :)
