### ISSUE TITLE
Numeric columns don't show a `0` value

### ISSUE THREAD

**Issue by lindseydiloreto** [mmikkel/DashCols-Craft#24]
I didn't dig into this one too deeply, but it appears that numeric columns don't show a `0` value. It's just blank instead.

Let me know if I'm mistaken! :)

**Comment by mmikkel** [comment]
Nice catch @lindseydiloreto – thanks! Fixed in v. 1.2.5 :)

**Comment by lindseydiloreto** [comment]
Sweet, thanks man!
