### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by samhibberd** [mmikkel/DashCols-Craft#4]
Would be great if you could format the display of the date field, but by default i think it should be the same as postDate?

ps Nice Plugin!!

**Comment by mmikkel** [comment]
Thanks for the kind words, much appreciated.

I've been meaning to improve the date/time output somehow, yeah. I don't know if formatting it exactly like postDate is the way to go - for starters I think the DashCols columns should include the _time_.

At some point I think DashCols will need to offer field formatting options - the Date/Time FieldType is a really good example where this would be a huge benefit. As long as the plugin uses the built-in Field Layout Designer - which, in all it's simplistic glory, is fairly limited - I'm not really sure how best to approach something like that, though. I might roll my own layout designer at some point, but not for a good while.

In the meantime, I'd be happy to hear people's suggestions for a decent, one-size-fits-most Date/Time format.

**Comment by samhibberd** [comment]
Would it be possible to provide date, time, or date / time based on the date field settings?

http://cl.ly/image/3b3s0z1W2O2E

**Comment by mmikkel** [comment]
Probably, though I'm pretty sure stuff like that would require fetching the actual _field_ as well as the field _data_ and I'm a little worried about overhead. It's definitely on the agenda, though.

**Comment by mmikkel** [comment]
Date/time columns now display date and/or time based on field settings – no performance hit.

Thanks for the suggestion @samhibberd :+1:
