### ISSUE TITLE
Bad request when CSRF protection is enabled

### ISSUE THREAD

**Issue by dralshehri** [mmikkel/DashCols-Craft#8]
I've enabled CSRF protection and I could not save DashCols fields settings. It return a  bad request error saying "The CSRF token could not be verified.". Perhaps updating forms with CSRF token is necessary in case if CSRF protection was enabled.

**Comment by mmikkel** [comment]
Thank you for reporting @dralshehri – I'll investigate ASAP!

**Comment by mmikkel** [comment]
This issue should now be resolved.
